-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 17:36:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema james
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema james
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `james` DEFAULT CHARACTER SET utf8 ;
USE `james` ;

-- -----------------------------------------------------
-- Table `james`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`user` (
  `user_id` INT NOT NULL,
  `user_account` VARCHAR(20) NULL,
  `user_type` TINYINT NULL,
  `login_type` TINYINT NULL,
  `user_profile_user_profile_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_profile_user_profile_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`user_profile` (
  `user_profile_id` INT NOT NULL,
  `user_id` INT NULL,
  `nickname` VARCHAR(20) NULL,
  `image_url` VARCHAR(100) NULL,
  `self_pr` VARCHAR(300) NULL,
  `join_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`user_profile_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`user_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`user_device` (
  `user_device_id` INT NOT NULL,
  `user_id` INT NULL,
  `in_use` TINYINT UNSIGNED NULL,
  `registration_order_no` TINYINT UNSIGNED NULL,
  `uuid` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `os_type` VARCHAR(20) NULL,
  `os_version` VARCHAR(20) NULL,
  PRIMARY KEY (`user_device_id`),
  INDEX `fk_user_device_user_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_device_user_log_device_id_idx` (`user_id` ASC, `user_device_id` ASC) VISIBLE, 
  CONSTRAINT `fk_user_device_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`user_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`user_password` (
  `user_password_id` INT NOT NULL,
  `user_id` INT NULL,
  `salt` VARCHAR(128) NULL,
  `password` VARCHAR(128) NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`user_password_id`),
  INDEX `fk_user_password_user_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_password_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`user_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`user_log` (
  `user_log_id` BIGINT NOT NULL,
  `user_id` INT NULL,
  `status_code` TINYINT NULL,
  `user_device_id` INT NULL,
  `user_ip` VARCHAR(15) NULL,
  `log` VARCHAR(300) NULL,
  `log_datetime` DATETIME NULL,
  PRIMARY KEY (`user_log_id`),
  INDEX `fk_user_log_user_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_log_user_device_user_device_id_idx` (`user_id` ASC, `user_device_id` ASC) VISIBLE, 
  CONSTRAINT `fk_user_log_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_log_user_device_user_device_id`
    FOREIGN KEY (`user_device_id` , `user_id`)
    REFERENCES `james`.`user_device` (`user_device_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`standby_dosa_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`standby_dosa_list` (
  `standby_dosa_list_id` BIGINT NOT NULL,
  `user_id` INT NULL,
  `status` TINYINT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`standby_dosa_list_id`),
  INDEX `fk_standby_dosa_list_user_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_standby_dosa_list_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`connection` (
  `connection_id` BIGINT NOT NULL,
  `caller_user_id` INT NULL,
  `receiver_user_id` INT NULL,
  `connect_start` DATETIME NULL,
  `connect_end` DATETIME NULL,
  `end_call_reason` VARCHAR(100) NULL,
  PRIMARY KEY (`connection_id`),
  INDEX `fk_connection_user_caller_user_id_idx` (`caller_user_id` ASC) VISIBLE,
  INDEX `fk_connection_user_receiver_user_id_idx` (`receiver_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_connection_user_caller_user_id`
    FOREIGN KEY (`caller_user_id`)
    REFERENCES `james`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connection_user_receiver_user_id`
    FOREIGN KEY (`receiver_user_id`)
    REFERENCES `james`.`standby_dosa_list` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `james`.`type_desc_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `james`.`type_desc_ref` (
  `type_desc_ref_id` INT NOT NULL,
  `type_category` TINYINT NULL,
  `type_num` TINYINT NULL,
  `type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`type_desc_ref_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
